# -*- coding: utf-8 -*-
"""Modul 4 Probabilitas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nkK6WIvyPdztsbAhn17PU4i24Dv8TsOJ
"""

from scipy import stats
X = stats.binom(15, 0.3)
print(X.pmf(5))           #P(X = 5)

print(X.cdf(2))     #P(X <= 2)

print(X.pmf(6)+X.pmf(7))

from scipy import stats
Y = stats.poisson(5)
print(Y.pmf(4))   #P(Y = 4)

from scipy import stats

#mendefinisikan variabel X sebagai distribusi binomial dengan 15 percobaan dan probabilitas sukses 0.1
X = stats.binom(20, 0.7)

#menghitung probabilitas massa X sama dengan 3
pmf_15 = X.pmf(15)

#mencetak nilai probabilitas
print(pmf_15)

from scipy import stats
Y = stats.poisson(2)

print(Y.pmf(3))   # \(P(Y=3)\)

